greeting:
  message: "hello"
  name: "quarkus"

quarkus:
  mongodb:
    connection-string: mongodb+srv://master:1234@cluster0.2elll.mongodb.net/<dbname>?retryWrites=true&w=majority
    database: consumer
